//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EstateManagementMvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Blocks_Units
    {
        public long Recno { get; set; }
        public System.Guid UnitId { get; set; }
        public string UnitName { get; set; }
        public System.Guid BlockId { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
    }
}
