//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EsoftPortalMvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_PaymentModes
    {
        public long Recno { get; set; }
        public string PaymentName { get; set; }
        public System.Guid tbl_PaymentID { get; set; }
    }
}
