//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EstateManagementMvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BranchSettings
    {
        public long Recno { get; set; }
        public string BranchCode { get; set; }
        public string Name { get; set; }
        public System.Guid BranchSettingsId { get; set; }
    }
}
