//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EstateManagementMvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company
    {
        public long Recno { get; set; }
        public string CompanyName { get; set; }
        public string CompanyAddress { get; set; }
        public string CompanyEmail { get; set; }
        public string CompanyTelephone { get; set; }
        public string CompanyPin { get; set; }
        public Nullable<decimal> Excise_Duty_Rate { get; set; }
        public Nullable<decimal> StampDuty { get; set; }
        public Nullable<decimal> WithholdingtaxRate { get; set; }
        public string WithholdingtaxAccount { get; set; }
        public string DisplayMessage { get; set; }
        public string Surplus_Loss_Account { get; set; }
        public string Teller_Slip_FooterText { get; set; }
        public Nullable<int> System_Lock_Out_time { get; set; }
        public System.Guid CompanyID { get; set; }
    }
}
