//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EstateManagementMvc.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Esoft_EstateEntities : DbContext
    {
        public Esoft_EstateEntities()
            : base("name=Esoft_EstateEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Company> Company { get; set; }
        public virtual DbSet<ProjectSettings> ProjectSettings { get; set; }
        public virtual DbSet<tbl_trail> tbl_trail { get; set; }
        public virtual DbSet<Tbl_UserRoles> Tbl_UserRoles { get; set; }
        public virtual DbSet<tbl_users> tbl_users { get; set; }
        public virtual DbSet<tbl_Blocks> tbl_Blocks { get; set; }
        public virtual DbSet<tbl_Blocks_Units> tbl_Blocks_Units { get; set; }
        public virtual DbSet<tbl_Buyers> tbl_Buyers { get; set; }
        public virtual DbSet<tbl_NavigationMenus> tbl_NavigationMenus { get; set; }
        public virtual DbSet<tbl_PasswordSettings> tbl_PasswordSettings { get; set; }
        public virtual DbSet<tbl_TellerAccounts> tbl_TellerAccounts { get; set; }
        public virtual DbSet<tbl_PasswordHistory> tbl_PasswordHistory { get; set; }
        public virtual DbSet<BranchSettings> BranchSettings { get; set; }
        public virtual DbSet<tbl_GlAccounts> tbl_GlAccounts { get; set; }
        public virtual DbSet<tbl_Ledger> tbl_Ledger { get; set; }
        public virtual DbSet<tbl_ModuleNames> tbl_ModuleNames { get; set; }
        public virtual DbSet<tbl_PaymentModes> tbl_PaymentModes { get; set; }
        public virtual DbSet<tbl_PostingReferences> tbl_PostingReferences { get; set; }
    }
}
